# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://julicavalcanti.github.io/'
baseurl: ''
title: "Juliana's blog"
description: 'This is my new blog'
permalink: pretty
logo: "https://pbs.twimg.com/media/Dj8XlmjV4AEzsvr.jpg"

# Gem settings
author: JulianaMoreira # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Juliana Moreira # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/juliana-c-moreira

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
# - title: Blog
#   url: /blog/
# - title: Posts by category
#   url: /categories/  


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/juliana-c-moreira
  RSS: /feed.xml

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

